# docker-compose.yml
version: '3.1'
services:
  db:
    # image: postgres:15.1
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data:rw
